# Generated by Django 5.0 on 2024-05-13 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordem_servico',
            fields=[
                ('id_ordem_servico', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_entrada', models.DateField()),
                ('data_conclusao', models.DateField()),
                ('descricao', models.CharField(max_length=400)),
                ('solicitante', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
                ('observacoes', models.CharField(max_length=200)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manutencoes.setor')),
            ],
        ),
    ]
