# Generated by Django 5.0 on 2024-05-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencoes', '0003_ordem_servico_numero_ordem_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem_servico',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordem_servico',
            name='observacoes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ordem_servico',
            name='status',
            field=models.CharField(choices=[('Aberta', 'Aberta'), ('Em espera', 'Em espera'), ('Concluída', 'Concluída'), ('Arquivada', 'Arquivada')], default='Aberta', max_length=40),
        ),
    ]
