# Generated by Django 5.0 on 2024-05-28 13:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencoes', '0004_alter_ordem_servico_data_conclusao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id_ordem_servico', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_ordem_servico', models.CharField(blank=True, max_length=50, unique=True)),
                ('data_entrada', models.DateField(default=django.utils.timezone.now)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('descricao', models.CharField(max_length=400)),
                ('solicitante', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('Aberta', 'Aberta'), ('Em espera', 'Em espera'), ('Concluída', 'Concluída'), ('Arquivada', 'Arquivada')], default='Aberta', max_length=40)),
                ('observacoes', models.CharField(blank=True, max_length=200)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manutencoes.setor')),
            ],
        ),
        migrations.DeleteModel(
            name='Ordem_servico',
        ),
    ]
